export const Strings ={
    tabs: "tabs", 
    home: "home",
    settings: "settings", 
    details: "details",
    dark: "dark",
    Light: "light",
    english: "english",
    arabic : "arabic",
    languageKey: "@languageKey",
    themeKet: "@themeKey",
    arKey: "ar",
    enKey: "en",
    textToggleLanguage:"textToggleLanguage",
    textToogleThemeMood:"textToogleThemeMood",
    API_KET: "e9a4934c51a940119b91329b8c658223",
    BASE_URL: "https://newsapi.org/v2/everything",
    searchPlaceHolder : "searchPlaceHolder",
}